AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lunora Player - Simple MediaLive Channel for RTMP Testing'

Parameters:
  ProjectName:
    Type: String
    Default: 'lunora-player'
    Description: 'Project name for resource naming'
  
  Environment:
    Type: String
    Default: 'prod'
    Description: 'Environment name'

  MediaPackageChannelId:
    Type: String
    Description: 'MediaPackage Channel ID from infrastructure stack'

  MediaLiveRoleArn:
    Type: String
    Description: 'MediaLive IAM Role ARN from infrastructure stack'

Resources:
  # MediaLive Input Security Group
  MediaLiveInputSecurityGroup:
    Type: AWS::MediaLive::InputSecurityGroup
    Properties:
      WhitelistRules:
        - Cidr: '0.0.0.0/0'
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  # MediaLive RTMP Input
  MediaLiveInput:
    Type: AWS::MediaLive::Input
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-rtmp-input'
      Type: 'RTMP_PUSH'
      InputSecurityGroups:
        - !Ref MediaLiveInputSecurityGroup
      Destinations:
        - StreamName: !Sub '${ProjectName}-${Environment}-stream'
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

  # MediaLive Channel
  MediaLiveChannel:
    Type: AWS::MediaLive::Channel
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-channel'
      RoleArn: !Ref MediaLiveRoleArn
      ChannelClass: 'SINGLE_PIPELINE'
      InputSpecification:
        Codec: 'AVC'
        Resolution: 'HD'
        MaximumBitrate: 'MAX_20_MBPS'
      InputAttachments:
        - InputAttachmentName: 'rtmp-input'
          InputId: !Ref MediaLiveInput
          InputSettings:
            AudioSelectors:
              - Name: 'default-audio'
                SelectorSettings:
                  AudioTrackSelection:
                    Tracks:
                      - Track: 1
            VideoSelector:
              ColorSpace: 'REC_709'
      Destinations:
        - Id: 'mediapackage-destination'
          MediaPackageSettings:
            ChannelId: !Ref MediaPackageChannelId
          Settings:
            - PasswordParam: ''
              Url: !Sub 'https://mediapackage.${AWS::Region}.amazonaws.com/in/v1/${MediaPackageChannelId}/channel'
              Username: ''
      EncoderSettings:
        TimecodeConfig:
          Source: 'EMBEDDED'
        AudioDescriptions:
          - AudioTypeControl: 'FOLLOW_INPUT'
            CodecSettings:
              AacSettings:
                Bitrate: 128000
                CodingMode: 'CODING_MODE_2_0'
                InputType: 'NORMAL'
                Profile: 'LC'
                RateControlMode: 'CBR'
                RawFormat: 'NONE'
                SampleRate: 48000
                Spec: 'MPEG4'
            LanguageCodeControl: 'FOLLOW_INPUT'
            Name: 'audio_1'
        VideoDescriptions:
          - CodecSettings:
              H264Settings:
                AdaptiveQuantization: 'HIGH'
                AfdSignaling: 'NONE'
                Bitrate: 5000000
                ColorMetadata: 'INSERT'
                EntropyEncoding: 'CABAC'
                FlickerAq: 'ENABLED'
                FramerateControl: 'SPECIFIED'
                FramerateNumerator: 30
                FramerateDenominator: 1
                GopBReference: 'DISABLED'
                GopClosedCadence: 1
                GopNumBFrames: 2
                GopSize: 90
                GopSizeUnits: 'FRAMES'
                Level: 'H264_LEVEL_AUTO'
                LookAheadRateControl: 'MEDIUM'
                NumRefFrames: 3
                ParControl: 'SPECIFIED'
                Profile: 'HIGH'
                RateControlMode: 'CBR'
                Syntax: 'DEFAULT'
                SceneChangeDetect: 'ENABLED'
                SpatialAq: 'ENABLED'
                TemporalAq: 'ENABLED'
            Height: 1080
            Name: 'video_1080p'
            RespondToAfd: 'NONE'
            ScalingBehavior: 'DEFAULT'
            Sharpness: 50
            Width: 1920
        OutputGroups:
          - Name: 'MediaPackage'
            OutputGroupSettings:
              MediaPackageGroupSettings:
                Destination:
                  DestinationRefId: 'mediapackage-destination'
            Outputs:
              - AudioDescriptionNames:
                  - 'audio_1'
                OutputName: 'output_1080p'
                OutputSettings:
                  MediaPackageOutputSettings: {}
                VideoDescriptionName: 'video_1080p'
      Tags:
        Project: !Ref ProjectName
        Environment: !Ref Environment

Outputs:
  MediaLiveChannelId:
    Description: 'MediaLive Channel ID'
    Value: !Ref MediaLiveChannel
    Export:
      Name: !Sub '${ProjectName}-${Environment}-medialive-channel-id'

  MediaLiveInputId:
    Description: 'MediaLive Input ID'
    Value: !Ref MediaLiveInput
    Export:
      Name: !Sub '${ProjectName}-${Environment}-input-id'

  RTMPEndpoint:
    Description: 'RTMP Endpoint for OBS'
    Value: !Sub 
      - 'rtmp://${InputEndpoint}/live/${ProjectName}-${Environment}-stream'
      - InputEndpoint: !Select [0, !GetAtt MediaLiveInput.Destinations]
    Export:
      Name: !Sub '${ProjectName}-${Environment}-rtmp-endpoint'

  RTMPServer:
    Description: 'RTMP Server for OBS'
    Value: !Sub 
      - 'rtmp://${InputEndpoint}/live'
      - InputEndpoint: !Select [0, !GetAtt MediaLiveInput.Destinations]
    Export:
      Name: !Sub '${ProjectName}-${Environment}-rtmp-server'

  RTMPStreamKey:
    Description: 'RTMP Stream Key for OBS'
    Value: !Sub '${ProjectName}-${Environment}-stream'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-rtmp-key'
