AWSTemplateFormatVersion: '2010-09-09'
Description: 'Robust SRT MediaConnect Flow with Multiple Outputs for Multi-MediaLive Distribution'

Parameters:
  ProjectName:
    Type: String
    Default: 'lunora-player'
    Description: 'Project name for resource naming'
  
  Environment:
    Type: String
    Default: 'prod'
    AllowedValues: ['dev', 'staging', 'prod']
    Description: 'Environment name'
  
  VideonSourceIP:
    Type: String
    Description: 'Videon Edge Node IP address for security (use 0.0.0.0/0 for testing)'
    Default: '0.0.0.0/0'
  
  SRTPort:
    Type: Number
    Default: 9998
    Description: 'SRT listener port'
    MinValue: 1024
    MaxValue: 65535

Resources:
  # MediaConnect Flow with SRT Input and Multiple RTP-FEC Outputs
  SRTMediaConnectFlow:
    Type: AWS::MediaConnect::Flow
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-srt-router'
      AvailabilityZone: !Sub '${AWS::Region}a'
      Source:
        Name: !Sub '${ProjectName}-videon-srt-source'
        Description: 'SRT input from Videon Edge Node'
        Protocol: 'srt-listener'
        IngestPort: !Ref SRTPort
        WhitelistCidr: !Ref VideonSourceIP
        MaxBitrate: 50000000  # 50 Mbps max
        # Note: Encryption will be configured separately if needed

  # Note: MediaLive channels will connect directly to the MediaConnect flow
  # No separate outputs needed - each MediaLive input will reference the flow ARN

  # CloudWatch Alarms for Monitoring
  MediaConnectFlowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-mediaconnect-flow-health'
      AlarmDescription: 'MediaConnect Flow Health Monitoring'
      MetricName: 'SourceHealth'
      Namespace: 'AWS/MediaConnect'
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: 'LessThanThreshold'
      Dimensions:
        - Name: 'FlowArn'
          Value: !GetAtt SRTMediaConnectFlow.FlowArn
      AlarmActions:
        - !Ref MediaConnectAlarmTopic
      TreatMissingData: 'breaching'

  # SNS Topic for Alerts
  MediaConnectAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-mediaconnect-alerts'
      DisplayName: 'MediaConnect Flow Alerts'

Outputs:
  MediaConnectFlowArn:
    Description: 'SRT MediaConnect Flow ARN'
    Value: !GetAtt SRTMediaConnectFlow.FlowArn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-srt-flow-arn'

  SRTIngestEndpoint:
    Description: 'SRT Ingest Endpoint for Videon'
    Value: !Sub 
      - 'srt://${IngestIp}:${Port}?streamid=lunora-primary-feed'
      - IngestIp: !GetAtt SRTMediaConnectFlow.Source.IngestIp
        Port: !Ref SRTPort
    Export:
      Name: !Sub '${ProjectName}-${Environment}-srt-ingest-endpoint'

  # MediaConnect Flow ARN for MediaLive channel configuration
  MediaConnectFlowArn:
    Description: 'MediaConnect Flow ARN for all MediaLive channels'
    Value: !GetAtt SRTMediaConnectFlow.FlowArn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-mediaconnect-flow-arn'

  MediaConnectAlarmTopicArn:
    Description: 'SNS Topic ARN for MediaConnect Alerts'
    Value: !Ref MediaConnectAlarmTopic
    Export:
      Name: !Sub '${ProjectName}-${Environment}-mediaconnect-alarm-topic'
